---
title: "🎣 Horgászvizsga"
---

Ez a leírás igyekszik némi segítséget nyújtani
az olyan horgászoknak, akik horgászvizsgájuk letétele
előtt állnak.

A vizsga általában feleletválasztós kérdésekből és halfajták
képről való felismeréséből áll.

## 📖 Tartalom

Három rövid és egyszerűen átlátható PDF a horgászvizsga tananyagából.
Továbbá egy hivatalos PDF a NÉBIH-től, ezt érdemes egyszer áttanulmányozni,
majd a vizsgára magunkkal vinni a másik két PDF-et, amig csak a lényeget
tartalmazzák.

- [Fontos felismerendő halak ⬇](https://github.com/krook1024/Horgaszvizsga/raw/master/FontosHalak.pdf)
- [Az összes vizsgán előforduló halfaj ⬇](https://github.com/krook1024/Horgaszvizsga/raw/master/Halak.pdf)
- [Tilalmi időszakok, méretkorlátozások, stb ⬇](https://github.com/krook1024/Horgaszvizsga/raw/master/Horgasz.pdf)
- [Teljes, NÉBIH által kiadott dokumentum ⬇](https://github.com/krook1024/Horgaszvizsga/raw/master/teljes.pdf)

Sok sikert és jó horgászatot!

## 🌍 Weboldal

A letölthető PDF állományokon kívül természetesen weboldal formájában
is elérhető az összes információ. A fenti menüvel lépkedhetünk
az oldalak között.

A weboldal a következő linken érhető el:  
[https://krook1024.github.io/Horgaszvizsga](https://krook1024.github.io/Horgaszvizsga)

# 🐟 🐠 🐡 🎣
